# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lilinzta's blog
subtitle: ''
description: ''
keywords:
author: Haotian Li
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://Lilinzta.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
navbar:
  blog_title: Lilinzta's blog
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

index:
  banner_img: /res/banner/home.png
  slogan:
    enable: true
    text: GOD'S IN HIS HEAVEN, ALL'S RIGHT WITH THE WORLD.

links:
  banner_img: /res/banner/link.png
  items:
    - {
      title: Xu Wei's blog,
      intro: Xu Wei's github page,
      link: 'https://victory1743123862.github.io/',
      avatar: '/res/link/wei.png'
    }
  default_avatar: /res/link/avatar.png

favicon: /res/favicon.png
apple_touch_icon: /res/favicon.png

post:
  banner_img: /res/banner/post.png
  meta:
    views:  # 阅读次数
      enable: false
      source: "busuanzi"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
  comments:
    enable: true
    type: gitalk
gitalk:
  clientID: 9d74ad43577ce767f34d
  clientSecret: bcb1e82eff718d70dfa74c53fe966ab7765dc3b2
  repo: Lilinzta.github.io
  owner: Lilinzta
  admin: ['Lilinzta']
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: false
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

archive:
  banner_img: /res/banner/archive.png

category:
  banner_img: /res/banner/category.png

tag:
  banner_img: /res/banner/tag.png

about:
  banner_img: /res/banner/about.png
  avatar: /res/about/avatar.jpg
  name: Haotian Li
  intro: A Arch Linux User
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Lilinzta', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/res/about/wechat.jpg' }
    - { class: 'iconfont icon-mail', link: 'mailto:lilinzta@gmail.com', tip: 'Gmail' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/lihaoti29952949', tip: 'X' }
    - { class: 'iconfont icon-telegram-fill', link: 'https://t.me/Lilinzta', tip: 'TG' }
    - { class: 'iconfont icon-rss', link: 'https://lilinzta.github.io/atom.xml', tip: 'RSS' }

rss: /atom.xml

footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
    <div style="font-size: 0.85rem">
      <span id="timeDate">载入天数...</span>
      <span id="times">载入时分秒...</span>
      <script src="/js/duration.js"></script>
    </div>
  '

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Lilinzta/Lilinzta.github.io.git
  branch: main
